# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b35bfd87b303a2572cf424d06806fc32bb82fef05c7ef780a584fb883582e6dc918f46fa407886aff65883733e0b0e29f8e513b238034bd122748d0cb851c2

test:
  secret_key_base: c4241d72d44759926efe4c86825f81fa43d40a8a4bebe4852f27709bf7ce40c1298734f058b327f1f684164a4ae5628effc69d71acc7b1b4f860b120e705397b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
